dev_addr: '10.250.0.11:8000'
edit_uri: edit/main/docs
site_dir: golden-config/static/golden-config/docs
site_name: Golden Configuration Documentation
#site_url: https://nbatest-mm.readthedocs.io/projects/golden-config/
repo_url: https://github.com/nautobot/nautobot-plugin-golden-config
copyright: Copyright &copy; 2022 The Authors
theme:
    name: material
    navigation_depth: 4
    custom_dir: overrides
    hljs_languages:
        - django
        - yaml
    features:
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - search.suggest
        - search.highlight
        - search.share
        - navigation.indexes
    favicon: assets/favicon.ico
    logo: assets/nautobot_logo.svg
    palette:
        # Palette toggle for light mode
        -   media: "(prefers-color-scheme: light)"
            scheme: default
            primary: black
            #accent: deep orange
            toggle:
                icon: material/weather-sunny
                name: Switch to dark mode

        # Palette toggle for dark mode
        -   media: "(prefers-color-scheme: dark)"
            scheme: slate
            primary: black
            #accent: deep orange
            toggle:
                icon: material/weather-night
                name: Switch to light mode
extra_css:
    - assets/extra.css
    #- assets/readthedocs-doc-embed.css
extra_javascript:
    - assets/jquery-3.6.0.min.js
    #- assets/theme.js
    #- assets/readthedocs-doc-embed.js

extra:
    generator: false
    ntc_sponsor: true
    social:
        -   icon: fontawesome/solid/rss
            link: https://blog.networktocode.com/blog/tags/nautobot
            name: NetworkToCode Blog
        -   icon: fontawesome/brands/slack
            link: https://www.networktocode.com/community/
            name: NetworkToCode Community
        -   icon: fontawesome/brands/twitter
            link: https://twitter.com/networktocode
            name: NetworkToCode Twitter
watch:
    - overrides
markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - attr_list
    - md_in_html
plugins:
    - search

nav:
    - Overview: 'index.md'
    - User Guide:
        - App Overview: 'user/app_overview.md'
        - Using the App: 'user/app_use_cases.md'
        - Navigate Backup: 'user/app_feature_backup.md'
        - Navigate Compliance: 'user/app_feature_compliance.md'
        - Navigate Compliance CLI: 'user/app_feature_compliancecli.md'
        - Navigate Compliance JSON: 'user/app_feature_compliancejson.md'
        - Navigate Compliance Custom: 'user/app_feature_compliancecustom.md'
        - Navigate Intended: 'user/app_feature_intended.md'
        - Navigate SoT Agg: 'user/app_feature_sotagg.md'
        - Getting Started: 'user/app_getting_started.md'
        - Frequently Asked Questions: 'user/app_faq.md'
        - External Interactions: 'user/app_external_interactions.md'
    - Administrator Guide:
        - Install and Configure: 'admin/admin_install.md'
        - Upgrade: 'admin/admin_upgrade.md'
        - Uninstall: 'admin/admin_uninstall.md'
        - Release Notes:
            - 'admin/release_notes/index.md'
            - v1.0: 'admin/release_notes/version_1.0.md'
            - v0.10: 'admin/release_notes/version_0.10.md'
            - v0.9: 'admin/release_notes/version_0.9.md'
    - Developer Guide:
        - Extending the App: 'dev/dev_extending.md'
        - Contributing to the App: 'dev/dev_contributing.md'
    - Nautobot Docs Home ↗︎: 'https://nbatest-ml.readthedocs.io/'
